/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (57.54%)
 * Likes:    1109
 * Dislikes: 306
 * Total Accepted:    243.8K
 * Total Submissions: 423.6K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 * Example 1:
 *
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 *
 * Example 2:
 *
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Example 3:
 *
 *
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 *
 * Example 4:
 *
 *
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 *
 *
 * Constraints:
 *
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 *
 *
 */

// @lc code=start
class Solution {
  public char findTheDifference(String s, String t) {
    var charCnt = new int[26];

    for (var ch : s.toCharArray()) {
      ++charCnt[ch - 'a'];
    }

    for (var ch : t.toCharArray()) {
      if (charCnt[ch - 'a'] == 0) {
        return ch;
      } else {
        --charCnt[ch - 'a'];
      }
    }

    return ' ';
  }
}
// @lc code=end
